version: '2'
services:
    quayps-app:
        image: quayps
        external_links:
            - quayps-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/quayps?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    quayps-mysql:
        extends:
            file: mysql.yml
            service: quayps-mysql
